# Test against these versions of Node.js
environment:
  matrix:
  - nodejs_version: "4.0"
  - nodejs_version: "4"
  - nodejs_version: "5.0"
  - nodejs_version: "5"
  - nodejs_version: "6.0"
  - nodejs_version: "6"

# Install scripts
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - node --version
  - npm --version
  - node -e "console.log(require('child_process').execFileSync(require('phantomjs25-beta').path, ['--version'], {encoding:'utf8'}));"

# Application test scripts
test_script:
  - npm test

# Don't actually build
build: off
